import logging

from fastapi import APIRouter, HTTPException, status
from sqlalchemy.exc import SQLAlchemyError

from app.core.dependencies import CurrentUser, DatabaseSession
from app.models.sql_audit import SQLAudit
from app.schemas.ai_query import (
    AIQueryRequest,
    AIQueryResponse,
)
from app.services.ai_query_service import (
    UnsafeGeneratedSQLError,
    process_ai_query,
)
from app.services.sql_generator import SQLGenerationError

logger = logging.getLogger(__name__)


router = APIRouter(
    prefix="/ai",
    tags=["AI Queries"],
)


@router.post(
    "/query",
    response_model=AIQueryResponse,
)
def query_data_with_ai(
    request_data: AIQueryRequest,
    db: DatabaseSession,
    current_user: CurrentUser,
) -> AIQueryResponse:
    try:
        result = process_ai_query(
            db=db,
            question=request_data.question,
        )

        audit = SQLAudit(
            user_id=current_user.id,
            sql_text=result.generated_sql,
            validation_passed=True,
            execution_success=True,
            row_count=result.row_count,
            execution_time_ms=result.execution_time_ms,
            error_message=None,
        )

        db.add(audit)
        db.commit()

        return AIQueryResponse(
            question=request_data.question,
            generated_sql=result.generated_sql,
            sql_explanation=result.sql_explanation,
            summary=result.summary,
            columns=result.columns,
            rows=result.rows,
            row_count=result.row_count,
            execution_time_ms=result.execution_time_ms,
            truncated=result.truncated,
        )

    except SQLGenerationError as exc:
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=str(exc),
        ) from exc

    except UnsafeGeneratedSQLError as exc:
        audit = SQLAudit(
            user_id=current_user.id,
            sql_text=exc.generated_sql,
            validation_passed=False,
            execution_success=False,
            row_count=0,
            execution_time_ms=None,
            error_message=str(exc),
        )

        db.add(audit)
        db.commit()

        logger.warning(
            "Unsafe SQL generated by LLM: user_id=%s, sql=%r, reason=%s",
            current_user.id,
            exc.generated_sql,
            str(exc),
        )

        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=(f"大模型生成的SQL未通过安全验证：{exc}"),
        ) from exc

    except SQLAlchemyError as exc:
        db.rollback()

        logger.exception(
            "AI generated SQL execution failed: user_id=%s",
            current_user.id,
        )

        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="AI生成的SQL执行失败",
        ) from exc
